load("@fbsource//tools/build_defs:rust_binary.bzl", "rust_binary")
load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("rankevolve")

rust_library(
    name = "rankevolve_cli_lib",
    srcs = glob(["**/*.rs"], exclude = ["bin/**"]),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
    ],
)

rust_binary(
    name = "rankevolve",
    srcs = ["bin/main.rs"],
    deps = [
        ":rankevolve_cli_lib",
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing-subscriber",
    ],
)
