load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("ads_ranking_features")

python_library(
    name = "chat_cli_lib",
    srcs = glob(
        ["**/*.py"],
        exclude = ["dual_inferencer_cli.py"],
    ),
    deps = [
        "fbsource//third-party/pypi/anthropic:anthropic",
        "fbsource//third-party/pypi/openai:openai",
        "fbsource//third-party/pypi/prompt-toolkit:prompt-toolkit",
        "fbsource//third-party/pypi/pyyaml:pyyaml",
        "fbsource//third-party/pypi/rich:rich",
        "//ai_productivity/plugboard/if:plugboard-if-python-clients",
        "//ai_productivity/plugboard/if:plugboard-if-python-types",
        "//ai_productivity/plugboard/if:stream_defs-python-types",
        # Auth & transport (all PUBLIC visibility)
        "//c2p/secure_thrift/python:client",
        "//configerator/structs/infrasec/if:acl-python-types",
        "//crypto/cat/py:corp_crypto_auth_token_util",
        # DualInferencer integration (agentic_foundation)
        "//rankevolve/src/agentic_foundation:agentic_foundation",
        "//rankevolve/src/server:server_lib",
        "//rankevolve/src/utils:utils",
        # Server business logic (shims re-export from server/)
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "//servicerouter/client/python:async_client",
            "//servicerouter/client/python:client_params",
        ],
    }),
)

python_binary(
    name = "chat_cli",
    main_function = "rankevolve.src.cli.chat_cli.main.main",
    deps = [
        ":chat_cli_lib",
    ],
)

python_binary(
    name = "dual_inferencer_cli",
    srcs = ["dual_inferencer_cli.py"],
    main_function = "rankevolve.src.cli.chat_cli.dual_inferencer_cli.main",
    deps = [
        "fbsource//third-party/pypi/click:click",
        "//rankevolve/src/agentic_foundation:agentic_foundation",
        "//rankevolve/src/utils:utils",
    ],
)
